sudo: required
dist: trusty

before_install:
  - sudo apt-get install apt-src
  # -s is required for installing from sources
  - sudo add-apt-repository -s 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe multiverse' -y
  - sudo apt-get update
  - sudo apt-src install criu

script: 
  - gradle test
  - sudo criu
