sudo: required
dist: trusty

install:
  - sudo apt-get install apt-src
  # -s is required for installing from sources
  - sudo add-apt-repository -s 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe multiverse' -y
  - sudo apt-get update
  #- sudo apt-src --build install criu
  - sudo apt-get source criu
  - sudo apt-get build-dep criu
  - sudo dpkg-buildpackage  -us -uc

script: 
  - gradle test
  - sudo sh -c 'which criu'
  - sudo sh -c 'criu'
